### ISSUE TITLE
Better control of Base / this constructors

### ISSUE THREAD

**Issue by jonmotos** [k94ll13nn3/AutoConstructor#107]
Is there a better way to control / specify which constructor is called in the generated constructor? I have two similar examples:

1. A class with two constructors: one with many parameters, one with no parameters. The one with no parameters is only to be used by the WPF designer, and so throws an exception. 
- Desired: The generated constructor (with parameters) should NOT call the parameterless constructor. I would expect to be able to configure this perhaps with an attribute?
2. A derived class with the same setup, and both derived and base class have each one constructor with no parameters, and one constructor with many parameters. It seems the generated constructor always tries to call the base(), with no parameters.
- Desired: The generated constructor should call the base constructor with the subset of parameters. Again I would expect to be able to configure this many ways: The generated constructor could call the base OR parameterless constructors.

Thanks!
By the way, what a great library for reducing constructor boilerplate!

**Comment by k94ll13nn3** [comment]
Before I work on this, can you confirm that this is the changes you would like. 

First I would like to know if you had a real case of a call to `base()` when the base class had 2 constructors, because at the moment, if a parent has more than 1 constructor, no `base` should be generated.

#### First case

```csharp
public class Class1
{
    public Class1(int i)
    {

    }

    public Class1()
    {
        
    }
}

[AutoConstructor]
public partial class Class2 : Class1
{
    private readonly int j;
}
```

In this case, you would like to be able to tell `Class2` to use `base(int)` or `base()`?

#### Second case (not really sure about what you described)

```csharp
public class Class1
{
    public Class1(int i)
    {

    }

    public Class1()
    {
        
    }
}

[AutoConstructor]
public partial class Class2 : Class1
{
    private readonly int j;

    public Class2() : base(0)
    {
    }
}
```

In this case, you would like to be able to tell `Class2` to use `this()` or `base()`?

**Comment by jonmotos** [comment]
Absolutely!
First case: parameterless constructor on self called from parameter constructor
Here's my actual setup:
```csharp
[AutoConstructor]
public partial class MyViewModel
{
  private readonly MyDependency _mine;

  public MyViewModel()
  {
    this.ThrowIfNotDesignTime();
  }

  //replaced by auto constructor
  //public MyViewModel(MyDependency mine)
  //{
  //  _mine = mine;
  //}
}
```
AutoConstructor currently calls this() on the parameterized constructor - I would like it to not.

Second case: Parent constructor calls parameterless base class constructor
Sorry for the confusion - here's my setup:
```csharp
[AutoConstructor]
public partial class MyViewModel : ViewModelBase
{
  private readonly MyDependency _mine;

  public MyViewModel() : base()
  {
    this.ThrowIfNotDesignTime();
  }

  //replaced by auto constructor
  //public MyViewModel(MyDependency mine, ILogger log) : base(log)
  //{
  //  _mine = mine;
  //}
}

[AutoConstructor]
public partial abstract class ViewModelBase
{
  private readonly ILogger _log;

  public ViewModelBase()
  {
    this.ThrowIfNotDesignTime();
  }

  //replaced by auto constructor - maybe
  //public ViewModelBase(ILogger log)
  //{
  //  _log = log;
  //}
}
```
Hopefully that clarifies this case! Currently the base() constructor is called instead - it would be ideal to specify which constructor was chosen. Perhaps in this case the base class MUST have an explicitly implemented constructor that could be decorated with an attribute indicating it should be chosen.

**Comment by k94ll13nn3** [comment]
Version [5.3.0-beta.1](https://www.nuget.org/packages/AutoConstructor/5.3.0-beta.1) is available with some new options:
- A new project configuration `AutoConstructor_GenerateThisCalls` that is defaulted to true that can disable `this` calls generation
- A new attribute `AutoConstructorDefaultBase` that, when put on a constructor, will be the default choice for `base` call
- A new option on `AutoConstructor` called `addDefaultBaseAttribute` that can generate the previous attribute when the constructor is auto-generated
- XML comments on attributes

This is far from done, as for example `ACONS02` is not detecting `AutoConstructorDefaultBase` or the option to generate `this` calls is not configurable class by class, but it is a starting point (work is tracked in #110).

**Comment by k94ll13nn3** [comment]
Version [5.3.0-beta.2](https://www.nuget.org/packages/AutoConstructor/5.3.0-beta.2) is available with all the features. I have some other work to do before 5.3.0, but all is done for this issue, and the non-beta version should be available this week-end.

**Comment by jonmotos** [comment]
Amazing. I was able to try beta.1 late last week and can say the project level config for this() works excellently. I will try the attribute level as well as the other features ASAP. Thank you again!

Perhaps as a note to others, I found that I had to close and re-open Visual Studio v17.8.4 in order for the source generator to reload and work correctly with the csproj configuration.
