### ISSUE TITLE
Bug: base and child class with the same parameter name

### ISSUE THREAD

**Issue by kentsday** [k94ll13nn3/AutoConstructor#123]
since version 2.5.1

if base class is injected `ILogger logger` and child class is injected `ILogger<T> logger`.
it will create two parameter for child class, but as we all know, it will fail to inject ILogger from MSDI.

in version 2.5.0, it will be ok to handle the issue a show above, because I can ajust the parameter order by myself to make it works.

**Comment by k94ll13nn3** [comment]
Hello, what version of this package are you using ? There is no version 2.5.1 or 2.5.0. Did you mean 5.2.1 and 5.2.0 ?

I've done some fixes yersterday about this specific case, so maybe you are talking about version 5.4.1 ?

Can you give a sample of what was working before and what is not working now ?

**Comment by kentsday** [comment]
> Hello, what version of this package are you using ? There is no version 2.5.1 or 2.5.0. Did you mean 5.2.1 and 5.2.0 ?
> 
> I've done some fixes yersterday about this specific case, so maybe you are talking about version 5.4.1 ?
> 
> Can you give a sample of what was working before and what is not working now ?

Sorry, I don't know why I typed 2.5.1.
It is 5.4.1 and 5.4.0. The new bug is raised due to the new fix.

classes:
```C#
[AutoConstructor]
public abstract partial class BaseClas
{
    private readonly ILogger _logger;
}

[AutoConstructor]
public sealed partial class ChildClass : BaseClas
{
    private readonly ILogger<ChildClass> _logger;
}
```

with 5.4.0, it works well as I expected.
```C#
    partial class ChildClass
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoConstructor", "5.0.0.0")]
        public ChildClass(Microsoft.Extensions.Logging.ILogger<Ex3.CryptoProviders.Solana.Tests.ChildClass> logger) : base(logger)
        {
            this._logger = logger;
        }
    }
```

with 5.4.1, it require a new `ILogger`, it is no ok.
```c#
    partial class ChildClass
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("AutoConstructor", "5.0.0.0")]
        public ChildClass(Microsoft.Extensions.Logging.ILogger<Ex3.CryptoProviders.Solana.Tests.ChildClass> logger, Microsoft.Extensions.Logging.ILogger b0__logger) : base(b0__logger)
        {
            this._logger = logger;
        }
    }
```

**Comment by k94ll13nn3** [comment]
It is what I was thinking you experienced. And it is not actually a bug, it is was it always should have been and it is what is expected since 5.4.1. I didn't think it would cause many problems because for the most parts, the code that have been fixed did not compile.

It only worked in your case because `ILogger<ChildClass>` inherits `ILogger`, but if your `BaseClass` had, let's say, a `ILogger<BaseClass>`, the code generated in 5.4.0 would have not compiled, whereas it does now. 

The fact that it worked was only because it was the same parameter name and by chance, the child type injected was inheriting the other, there is no type inheritance checking in this library.

Can you change the `ILogger` in your base class to `ILogger<BaseClass>` ?

**Comment by kentsday** [comment]
@k94ll13nn3 
it could be `ILogger<BaseClass>`, it works. but in in 5.4.1 it would inject two loggers into a class, and making logger is hard to filter. the T in `ILogger<T>` is used to identify the logger and will append to logging system.
so even using `ILogger<BaseClass>` would compile success, but to inject two loggers into a service it not a good practice this in case.
FYI: <https://stackoverflow.com/questions/60344757/base-class-type-for-iloggert-using-dependency-injection>

**Comment by kentsday** [comment]
However, it is indeed difficult to judge because it seems impossible to determine the inheritance relationship between ILoggers at the stage of SG.
If it's okay, I think you can add some attributes. Yes, the development can freely control whether to inject new ones or use the same ones. In that case, there may be no problem.

**Comment by k94ll13nn3** [comment]
I will see what I can do to allow you to override the current behavior in order to have only one logger.

**Comment by k94ll13nn3** [comment]
Version `5.5.0-beta.1` is available with a new parameter `matchBaseParameterOnName` on `AutoConstructor`.

You can replace you child code with this and it should be back as it was.
```csharp
[AutoConstructor(matchBaseParameterOnName: true)]
public sealed partial class ChildClass : BaseClas
{
    private readonly ILogger<ChildClass> _logger;
}
```

Let me know what you think of this solution before I release a new version.

**Comment by kentsday** [comment]
Thanks, you are really helpful! 
`5.5.0-beta.1` works as I expected.
