### ISSUE TITLE
Support Nested Classes

### ISSUE THREAD

**Issue by lbrecheisen** [k94ll13nn3/AutoConstructor#13]
Seems there is no support for nested classes.
```c#
public static class Example
{
    [AutoConstructor]
    public partial class Nested
    {
        private readonly IDependency Dependency;
    }
}
```
Bit of a niche use case, but can make since when using an outer class to group by vertical slice.

**Comment by k94ll13nn3** [comment]
Support for nested classes has been added.
You can check the newly released 2.2.0 version.
