### ISSUE TITLE
Code coverage report not generating

### ISSUE THREAD

**Issue by msteponavicius** [k94ll13nn3/AutoConstructor#57]
Hello,

We're using _dotnet test --collect:"XPlat Code Coverage"_ to generate a code coverage report for our tests. However, it seems that just adding the AutoConstructor package causes the report to be empty:

```
<?xml version="1.0" encoding="utf-8"?>

<coverage line-rate="0" branch-rate="0" version="1.9" timestamp="1679657152" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0">

  <sources />

  <packages />

</coverage>
```

**Comment by DomasM** [comment]
https://github.com/coverlet-coverage/coverlet/issues?q=is%3Aissue+is%3Aopen+%22source+generator%22+

**Comment by k94ll13nn3** [comment]
Hello, I looked at some issues in the link provided by @DomasM, and it seems related to the the filename of the generated files (see https://github.com/coverlet-coverage/coverlet/issues/1262 for example), but the files generated by AutoContructor are named in `*.g.cs` like coverlet need, so I'm not sure what other fix is needed.

**Comment by DomasM** [comment]
@k94ll13nn3 what I wanted to say is that coverlet is having issues with source generators in general and this isn't specific problem of AutoConstructor as far as I understand.

**Comment by DomasM** [comment]
This is no longer a problem with coverlet 6.0.0, so I think we can close it.
