### ISSUE TITLE
Fails to call base constructor if base has static constructor

### ISSUE THREAD

**Issue by DomasM** [k94ll13nn3/AutoConstructor#60]
Adding static field to base class will add implicit static constructor to this class and method _ExtractFieldsFromParent_ fails to extract fields from this class

`        if (baseType?.BaseType is not null && baseType?.Constructors.Length == 1)
`
as there are two constructors now, even if one is implicit static one.

This affect analyzer too.

Simplest repo:

```
 class TestBase{
    private static readonly int _s_t5=1;
    private readonly int _t1;

    public TestBase(int t1){
        this._t1 = t1;
    }
  }

 [AutoConstructor]
  internal partial class Test : TestBase
    {
    }
```

**Comment by k94ll13nn3** [comment]
Fixed by #61
