### ISSUE TITLE
The source generator is completely non incremental

### ISSUE THREAD

**Issue by Sergio0694** [k94ll13nn3/AutoConstructor#82]
Just FYI, the incremental pipeline of the source generator is completely broken (as in, it's not incremental at all). This will have awful performance, as source files will be recomputed for every single edit. Additionally, this will unnecessarily root compilation objects, increasing memory use.

The problematic line is this (among others):

https://github.com/k94ll13nn3/AutoConstructor/blob/b6d4d3de4642d4d156586c367564feb21703c9d5/src/AutoConstructor.Generator/AutoConstructorGenerator.cs#L36

You should _never_ have any compilations or symbols in _any_ steps of your incremental pipelines, and especially in output steps. Those objects are not equatable and not meant to be used this way.

**Comment by k94ll13nn3** [comment]
Thank you for taking the time to look at that. 
I will look at it, I think I was not totally aware of all of this when i made the switch from the old model to the incremental model, so it does not suprise me that I did not made the right code.
